FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем нужные файлы
COPY webhook_server.py .
COPY database.py .

# Запускаем только вебхук-сервер
CMD ["python", "webhook_server.py"]
